version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=drones
            - POSTGRES_PASSWORD=drones
            - POSTGRES_DB=drones
        container_name: drones_db

    app:
        image: napolesqva/drones
        restart: always
        environment:
            - DEBUG=1
            - PRODUCTION=0
            - SECRET_KEY=django-insecure-7@^sc)4+m*=bvhkz++%#$l(db74h)u-4l4=7$v&c8bp%d2b-64
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
        depends_on:
            - db
        container_name: drones

    redis:
        image: redis
        ports:
            - "6379:6379"
        container_name: drones_redis

    celery_worker:
        restart: always
        environment:
            - DEBUG=1
            - PRODUCTION=0
            - SECRET_KEY=django-insecure-7@^sc)4+m*=bvhkz++%#$l(db74h)u-4l4=7$v&c8bp%d2b-64
        image: napolesqva/drones
        command: celery -A config worker --loglevel=info --logfile=logs/celery.log
        depends_on:
            - db
            - redis
            - app
        container_name: drones_celery_worker

    celery-beat:
        image: napolesqva/drones
        environment:
            - DEBUG=1
            - PRODUCTION=0
            - SECRET_KEY='django-insecure-7@^sc)4+m*=bvhkz++%#$l(db74h)u-4l4=7$v&c8bp%d2b-64'
        command: celery -A config beat -l info
        depends_on:
            - db
            - redis
            - app
        container_name: drones_celery_beat

    flower:
        image: napolesqva/drones
        environment:
            - DEBUG=1
            - PRODUCTION=0
            - SECRET_KEY=django-insecure-7@^sc)4+m*=bvhkz++%#$l(db74h)u-4l4=7$v&c8bp%d2b-64
        command: celery -A config flower  --broker=redis://host.docker.internal:6379//
        ports:
            - 5555:5555
        depends_on:
            - db
            - app
            - redis
            - celery_worker
        container_name: drones_flower

volumes:
    postgres_data:
