# Generated by Django 3.2.9 on 2022-05-28 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 28, 4, 51, 42, 698585, tzinfo=utc), help_text='Date Start Delivery', null=True),
        ),
    ]
