# Generated by Django 3.2.9 on 2022-05-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Processed', 'Processed'), ('Success', 'Success'), ('Error', 'Error')], default='Processing', help_text="Delivery State Choices default='Processing'", max_length=13),
        ),
    ]
